services:
  db:
    image: ${DB_IMAGE}
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_HOST_IP}:${DB_PORT_EXTERNAL}:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    networks:
      - db_internal_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  scheduler:
    build: .
    container_name: ${DB_CONTAINER_NAME}_scheduler
    depends_on:
      - db
    environment:
      - TZ=${TZ}
    command: daemon --docker --docker-filter "label=ofelia.scope=${DB_CONTAINER_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/project:ro
    labels:
      ofelia.scope: "${DB_CONTAINER_NAME}"
      ofelia.job-local.db-backup.schedule: "0 0 3 * * *"
      ofelia.job-local.db-backup.command: "/bin/sh -lc 'cd /project && ./scripts/backup.sh'"
    networks:
      - db_internal_network

networks:
  db_internal_network:
    name: ${DB_CONTAINER_NAME}_net
